#!/bin/bash
# Cyptex128 Quick Start Guide

echo "+----------------------------------------------------------------+"
echo "|                        CYPTEX128 QUICK START                    |"
echo "+----------------------------------------------------------------+"
echo ""
echo "Building in release mode..."
cargo build --release

echo ""
echo "Build complete."
echo ""
echo "Quick test examples:"
echo ""
echo "1. Basic hash:"
echo "   ./target/release/cyptex128 hash 'Hello, Cyptex128!'"
echo ""
echo "2. Hash with stats:"
echo "   ./target/release/cyptex128 hash 'Cyptex128' --stats"
echo ""
echo "3. Run benchmarks:"
echo "   ./target/release/cyptex128 bench --iterations 5000000"
echo ""
echo "4. Encrypt/Decrypt:"
echo "   CIPHER=\$(./target/release/cyptex128 encrypt 'test' 'sixteen-byte-key' --hex)"
echo "   ./target/release/cyptex128 decrypt \$CIPHER 'sixteen-byte-key' --text"
echo ""
echo "5. Hash from file:"
echo "   echo 'test data' > test.txt"
echo "   ./target/release/cyptex128 hash --file test.txt"
echo ""
echo "6. Full help:"
echo "   ./target/release/cyptex128 info"
echo ""
